# Generated by Django 3.1.3 on 2020-11-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaApp', '0002_auto_20201126_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='iimage_url',
            new_name='image_url',
        ),
    ]
