# Generated by Django 3.1.3 on 2020-11-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaApp', '0005_auto_20201126_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
