# Generated by Django 3.1.3 on 2020-11-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaApp', '0006_auto_20201126_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
