# Generated by Django 3.1.3 on 2020-11-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaApp', '0007_auto_20201126_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='like_add',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
